### ISSUE TITLE
Supporting non-postgres DBs

### ISSUE THREAD

**Issue by hokadiri** [tektoncd/results#158]
### Feature request
Ability to use Requests with non-Postgres DB

### Use case

I see in [v0.3.0](https://github.com/tektoncd/results/releases/tag/v0.3.0), the DB was moved from mysql to postgres and the reason -- from #121 -- is because of postgres support of Json types. Mysql does [support](https://dev.mysql.com/doc/refman/8.0/en/json.html) json types.
 
Are there plans for folks who can't use postgres (due to say company policy) to be able to use Results?

**Comment by wlynch** [comment]
(this was also asked on Slack, so copying my reply here):

IIRC, it looked like JSON data was going to be able to be more easily manipulated and queried with postgres rather than mysql - it’s also very possible that assumption was completely wrong :upside_down_face:

I’m open to re-adding mysql support as an alternative backend (happy to review, though I personally won’t have the bandwidth to impl it :disappointed:). At the time we were focused on having 1 backend that works, and postgres just seemed like the clearer path.
