### ISSUE TITLE
Integration of Knative Adapter for Enhanced Logging in Tekton Results API

### ISSUE THREAD

**Issue by ramessesii2** [tektoncd/results#669]
### Feature request

This issue proposes the integration of a Knative adapter to enhance logging capabilities within the Tekton Results API component. This transition aims to address the limitations and lack of uniformity in logging across the API and watcher currently observed with the zap logger.
Original Issue  - #272 

### Use case

The Tekton Results API employs a zap logger, which has demonstrated limitations and inconsistencies, particularly in uniformity across the API and watcher components. Adopting a Knative-based logging approach, inspired by its successful use in Tekton Triggers and Pipelines-as-Code projects, promises enhanced flexibility, integration, and customization.

### Benefits

- Standardized and uniform logging across different components.
- Enhanced configurability using Kubernetes ConfigMaps, allowing dynamic adjustments at runtime.

### Potential Drawbacks
- Dependency on the Kubernetes client.
- We'll still need a middle-ware in cases like fetching context in the RBAC pkg of Results API.

### Preliminary configuration of adapter with Tekton-Results API 
https://github.com/ramessesii2/downstream-tektoncd-results/blob/RAMESSESII2/results-api-knative-adapter-2/cmd/api/main.go

**Comment by ramessesii2** [comment]
cc @khrm @enarha @sayan-biswas @avinal

**Comment by sayan-biswas** [comment]
Few things here i would like to mention..

- Using the adapter would require us to change the current way of parsing config (which is currently handled by viper), if we want to use the configmap handler provided by knative.
- This approach won't provide the benefit of injecting the logger and configurations in the context, as with the current  code the same context is not propagated in the handlers. Although we can use a middleware to insert that context in the chain, but that we can can simply do that without using the knative adapter complexities, since we know that knative also uses `zap` logger underneath.

**Comment by ramessesii2** [comment]
Agreeing with the @sayan-biswas's feedback, I'm closing this issue. 
The integration of a Knative adapter doesn't align with our current viper-based config parsing and context propagation needs in Tekton Results API . The complexities added by this approach, given our reliance on the zap logger, outweigh the benefits.
